---
title: "eds212-day2-activities"
author: "Kimmy Wong"
format: html
editor_options: 
  chunk_output_type: console
---

# load packages
```{r}
library(palmerpenguins)

library(tidyverse)
```

# add git stuff

usethis::use_git()

usethis::use_github()

# find derivatives
```{r}
exp1<-expression(x^2)

exp1_der<-D(exp1,'x')

x=3

eval(exp1_der)
```

```{r}
exp2<-expression((2*(3*a+2)^4)-5)

exp2_der<-D(exp2,'a')

a=1.2
  
eval(exp2_der)
```

# make penguin plot of bill length v. bill depth
```{r}
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_point(aes(color = species)) +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  labs(x = "Bill Length (mm)",
       y = "Bill Depth (mm)",
       title = "Palmer Penguin Bill Length in relation to Bill Depth",
       subtitle = "Palmer Archipelago, Antarctice (2007 - 2009)",
       caption = "Collected by Dr. Kristen Gorman and colleagues at Palmer Station LTER") 
```


# make penguin plot of species v flipper length
```{r}
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
  geom_point(aes(color = species)) +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  labs(x = "Species",
       y = "Flipper length (mm)",
       title = "Palmer Penguin Flipper Length Measurements by Species",
       subtitle = "Palmer Archipelago, Antarctice (2007 - 2009)",
       caption = "Collected by Dr. Kristen Gorman and colleagues at Palmer Station LTER") 

boop
```


